In [16]:
from pandas import *
df = read_csv('number-of-deaths-by-risk-factor.csv')
df.head(10)

,Entity,Code,Year,Unsafe water source (deaths),Poor sanitation (deaths),No access to handwashing facility (deaths),Indoor air pollution (deaths),Non-exclusive breastfeeding (deaths),Discontinued breastfeeding (deaths),Child wasting (deaths),...,Air pollution (outdoor & indoor) (deaths),Outdoor air pollution (deaths),Diet low in fiber (deaths),Diet high in sodium (deaths),Diet low in legumes (deaths),Diet low in calcium (deaths),Diet high in red meat (deaths),Diet low in whole grains (deaths),Diet low in nuts and seeds (deaths),Diet low in seafood omega-3 fatty acids (deaths)
0,Afghanistan,AFG,1990,7554.049543,5887.747628,5412.314513,22388.497233,3221.138842,156.097553,22778.849249,...,26598.006727,4383.83,2864.234512,2737.197934,3418.965194,181.287701,0.220484,11381.377345,7299.867330,6456.565238
1,Afghanistan,AFG,1991,7359.676749,5732.770160,5287.891103,22128.758206,3150.559597,151.539851,22292.691113,...,26379.532218,4426.36,2974.479775,2741.184956,3457.398250,184.251584,0.184714,11487.832390,7386.764303,6511.344276
2,Afghanistan,AFG,1992,7650.437822,5954.804987,5506.657363,22873.768789,3331.349048,156.609194,23102.197940,...,27263.127914,4568.91,3168.591633,2798.560245,3586.490291,191.318450,0.151354,11866.235572,7640.628526,6703.095594
3,Afghanistan,AFG,1993,10270.731383,7986.736613,7104.620351,25599.756284,4477.006100,206.834451,27902.669960,...,30495.561499,5080.29,3401.045056,2853.301679,3746.266658,199.767293,0.109392,12335.961682,7968.311853,6946.196824
4,Afghanistan,AFG,1994,11409.177112,8863.010065,8051.515953,28013.167200,5102.622054,233.930571,32929.005932,...,33323.161401,5499.23,3599.709735,2880.025765,3869.288402,206.619714,0.059103,12672.950191,8244.368430,7138.030745
5,Afghanistan,AFG,1995,12676.647424,9840.848680,8770.686294,29062.618787,5402.660379,262.793340,35631.997028,...,34511.845284,5641.29,3732.598460,2892.221692,3935.209932,211.137298,0.039922,12854.592679,8375.861883,7225.040846
6,Afghanistan,AFG,1996,12154.942315,9426.896445,8610.686857,29407.321601,5263.644458,253.668181,36114.593233,...,34952.101583,5739.07,3877.026009,2905.798225,4019.906785,215.778490,0.026291,13089.157280,8537.651676,7336.080630
7,Afghanistan,AFG,1997,12329.131710,9553.555998,8722.943079,29674.398315,5271.771800,258.134146,36749.117453,...,35306.566595,5828.94,4017.069696,2919.683894,4104.371202,220.586247,0.017090,13326.500377,8694.523034,7446.826074
8,Afghanistan,AFG,1998,12133.609541,9390.042030,8621.884918,29807.453214,5165.923779,254.708078,36569.465573,...,35360.168867,5751.54,4137.050160,2925.391235,4173.597768,224.793817,0.010725,13516.547571,8818.249272,7532.322210
9,Afghanistan,AFG,1999,11990.396328,9268.489611,8502.729990,29484.612215,5044.307573,251.898824,36124.046557,...,35040.349506,5756.43,4211.727042,2936.213764,4201.930953,229.298613,0.007501,13584.239432,8867.619444,7553.269512

In [18]:
df.dtypes

Entity                                               object
Code                                                 object
Year                                                  int64
Unsafe water source (deaths)                        float64
Poor sanitation (deaths)                            float64
No access to handwashing facility (deaths)          float64
Indoor air pollution (deaths)                       float64
Non-exclusive breastfeeding (deaths)                float64
Discontinued breastfeeding (deaths)                 float64
Child wasting (deaths)                              float64
Child stunting (deaths)                             float64
Low birth weight (deaths)                           float64
Secondhand smoke (deaths)                           float64
Alcohol use (deaths)                                float64
Drug use (deaths)                                   float64
Diet low in fruits (deaths)                         float64
Diet low in vegetables (deaths)                     float64
Unsafe sex (deaths)                                 float64
Low physical activity (deaths)                      float64
High blood sugar (deaths)                           float64
High cholesterol (deaths)                           float64
Obesity (deaths)                                    float64
High blood pressure (deaths)                        float64
Smoking (deaths)                                    float64
Iron deficiency (deaths)                            float64
Zinc deficiency (deaths)                            float64
Vitamin-A deficiency (deaths)                       float64
Low bone mineral density (deaths)                   float64
Air pollution (outdoor & indoor) (deaths)           float64
Outdoor air pollution (deaths)                      float64
Diet low in fiber (deaths)                          float64
Diet high in sodium (deaths)                        float64
Diet low in legumes (deaths)                        float64
Diet low in calcium (deaths)                        float64
Diet high in red meat (deaths)                      float64
Diet low in whole grains (deaths)                   float64
Diet low in nuts and seeds (deaths)                 float64
Diet low in seafood omega-3 fatty acids (deaths)    float64
dtype: object